{% set name = "transformers" %} 
{% set version = "3.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/huggingface/transformers.git
  git_rev: v{{ version }}

build:
  noarch: python
  number: 5
  string: py_pb{{ protobuf | replace(".*", "")}}_{{ PKG_BUILDNUM }}
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '
  ignore_run_exports:
    - libgcc-ng
    - libstdcxx-ng

requirements:
  build:
    - git >={{ git }}
    # Use pins to control cos6/cos7 match
    - libgcc-ng  {{ libgcc }}
    - libstdcxx-ng  {{ libstdcxx }}

  host:
    - pip {{ pip }}
    - python
    # Use pins to control cos6/cos7 match
    - libgcc-ng  {{ libgcc }}
    - libstdcxx-ng  {{ libstdcxx }}

  run:
    - filelock  
    - numpy {{ numpy }}
    - python 
    - regex {{ regex }}
    - requests {{ requests }}
    - sacremoses
    - sentencepiece {{ sentencepiece }}
    - protobuf {{ protobuf }}
    - tokenizers {{ tokenizers }}
    - tqdm {{ tqdm }}
    - dataclasses                         #[py36]
    - packaging
    # Use pins to control cos6/cos7 match
    - libgcc-ng  {{ libgcc }}
    - libstdcxx-ng  {{ libstdcxx }}

test:
  imports:
    - transformers
    - transformers.commands
    - transformers.data
    # - transformers.data.datasets  # skip; would require PyTorch as install pre-req
    - transformers.data.metrics
    - transformers.data.processors
  commands:
    - python $CONDA_PREFIX/bin/transformers-cli --help
  requires:
    - pytest

about:
  home: https://github.com/huggingface/transformers
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: State-of-the-art Natural Language Processing for TensorFlow 2.0 and PyTorch
  doc_url: https://huggingface.co/transformers/
  description: |
    State-of-the-art Natural Language Processing for PyTorch and TensorFlow 2.0

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
